name: build latest docker

on:
  push:
    branches: master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build the Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.PackageRegistry }}
        run: |
          docker login docker.pkg.github.com --username XGFan --password $GITHUB_TOKEN
          docker build . --file Dockerfile --tag docker.pkg.github.com/xgfan/fund-watcher:latest
          docker push docker.pkg.github.com/xgfan/fund-watcher:latest
